### ISSUE TITLE
getting error when running this docker container

### ISSUE THREAD

**Issue by caymann12** [marc1307/tailscale-cloudflare-dnssync#24]
root@docker:~# docker run --rm -it --env-file /root/git/tailscale-cloudflare-dnssync/env.txt ghcr.io/marc1307/tailscale-cloudflare-dnssync:latest
Traceback (most recent call last):
  File "app.py", line 96, in <module>
    main()
  File "app.py", line 15, in main
    cf_ZoneId = getZoneId(config['cf-key'], config['cf-domain'])
  File "/app/cloudflare.py", line 20, in getZoneId
    exit(colored('getZoneId(): '+json.dumps(data['errors'], indent=2)), "red")
TypeError: __call__() takes from 1 to 2 positional arguments but 3 were given

**Comment by asterixix** [comment]
same here during docker run

sudo docker run --rm -it --env-file ~/git/tailscale-cloudflare-dnssync/env.txt ghcr.io/marc1307/tailscale-cloudflare-dnssync:latest
Traceback (most recent call last):
  File "app.py", line 96, in <module>
    main()
  File "app.py", line 15, in main
    cf_ZoneId = getZoneId(config['cf-key'], config['cf-domain'])
  File "/app/cloudflare.py", line 20, in getZoneId
    exit(colored('getZoneId(): '+json.dumps(data['errors'], indent=2)), "red")
TypeError: __call__() takes from 1 to 2 positional arguments but 3 were given

**Comment by marc1307** [comment]
Hi, this likely is due to a invalid cloudflare token. I've fixed the exit() function, it shows something useful now.
